### ISSUE TITLE
ThemeProvider theme passing not working

### ISSUE THREAD

**Issue by mrceperka** [rofrischmann/fela#252]
**Version**: 4.3.3
**Environment**: DOM
**Type**: Bug
**React version**: 15.4.2

-------------------
#### Description
Hello, I've experienced issue with `ThemeProvider`.
It looks like it is passing **empty theme** to children.
I've setup [an example at github](https://github.com/mrceperka/react-fela-theme-not-working).
This might not be a bug, maybe just a bad setup of Fela and React and I am the one to blame.

Thanks for help.

#### Steps to reproduce
1. `git clone https://github.com/mrceperka/react-fela-theme-not-working`
2. `cd react-fela-theme-not-working`
3. `yarn install`
4. `yarn start`
5. Visit [localhost:3000](http://localhost:3000) and see `console`

#### Expected Behavior
Non empty `theme` should be passed

#### Actual Behavior
Empty `theme` passed

**Comment by rofrischmann** [comment]
Is fixed with the new release, got broken in 4.3.3

**Comment by mrceperka** [comment]
Thank you! :fireworks:

**Comment by mrceperka** [comment]
It looks like it still not working.
Previous code was like this:
```
const Root = props => (
  <FelaProvider renderer={getRenderer()} mountNode={getMountNode()}>
    <ThemeProvider theme={theme}>
      <App />
    </ThemeProvider>
  </FelaProvider>
);
```

Now I have to pass renderer to `ThemeProvider` to get rid of
`Error: createComponent() can't render styles without the renderer in the context. Missing react-fela's <Provider /> at the app root?`

So I've modified code to this (to silence the error :no_bell: )
```
const Root = props => (
  <FelaProvider renderer={getRenderer()} mountNode={getMountNode()}>
    <ThemeProvider theme={theme} renderer={getRenderer()}>
      <App />
    </ThemeProvider>
  </FelaProvider>
);
```

But `theme` is still **empty**. I've updated example [repo](https://github.com/mrceperka/react-fela-theme-not-working). What am I doing wrong?

Thanks for help.

**Comment by rofrischmann** [comment]
OMG, my bad. I accidently replaced <ThemeProvider> with <Provider> 😅 next release is coming
