### ISSUE TITLE
Wrong order of style elements on react-fela

### ISSUE THREAD

**Issue by josemussa** [rofrischmann/fela#579]
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| react-fela     | 7.x.x   |

-------------------
#### Description
When you create components using `createComponent` or `createComponentWithProxy` and your renderer is enhanced with `fela-monolithic` the order of the style elements is wrong, this is explicitly obvious when you're using media queries:
<img width="524" alt="screen shot 2018-06-20 at 2 40 47 pm" src="https://user-images.githubusercontent.com/4422500/41658869-0952ce20-7498-11e8-9412-425fac839ebf.png">
So the style element with no media query is created after all the media queries, this results on the layout breaking.

On react-fela 6.x.x the style elements are created this way:
<img width="526" alt="screen shot 2018-06-20 at 2 44 16 pm" src="https://user-images.githubusercontent.com/4422500/41659040-7dc265f4-7498-11e8-8666-cae27d755e7d.png">
Giving us a fully functional layout.

##### Your component
```JS
const rule = () => ({
  width: '100%',
  height: '100%',

  '@media (min-width: 768px)': {
    width: 700
  },
  '@media (min-width: 1024px)': {
    width: 1000
  }
})

const ResponsiveComponent = createComponent(rule, 'div')
```
##### Your renderer
```JS
import monolithic from 'fela-monolithic'

const config = {
  enhancers: [ monolithic() ]
}

const renderer = createRenderer(config)
```

**Comment by rofrischmann** [comment]
This should be fixed as soon as #573 merged. 
But keep in mind that `fela-monolithic` is not intended to be used in production. It does not guarantee that everything works perfectly in production.

**Comment by rofrischmann** [comment]
Would be great to retry this now.

**Comment by AgtLucas** [comment]
@rofrischmann Still the same issue after upgrading fela...

Here's my renderer:

```js
const renderer = createRenderer({
  plugins: [embedded(), prefixer(), fallbackValue()],
  mediaQueryOrder: [
    '@media only screen and (min-width:0px)',
    '@media only screen and (min-width:320px)',
    '@media only screen and (min-width:768px)',
    '@media only screen and (min-width:1024px)',
    '@media only screen and (min-width:1200px)',
  ],
});
```
Here's the result:

<img width="889" alt="screen shot 2018-08-20 at 08 39 40" src="https://user-images.githubusercontent.com/1909761/44324070-ac510880-a454-11e8-8fcc-1c01206ebee6.png">

The same happens if I remove `mediaQueryOrder` completely, so I'm wondering maybe it's something wrong in our implementation. 🤔

With the older `fela` version, I manage to figure out a work around for this, that was to declare all breakpoints in at least 1 component's rule, so the order would be right, but after the upgrade, that solution isn't working anymore...
